[build]
  command = "npm install && npm run build"
  publish = "frontend/build"
  functions = "backend/functions"  # ✅ Ensure correct function path

[dev]
  command = "npm start"
  port = 3000
  functionsPort = 8888
