[build]
  command = "npm install && npm run build"  # ✅ Install dependencies & build
  publish = "build"  # ✅ Netlify serves frontend from here
  functions = "backend"  # ✅ Netlify functions are inside `backend/`

[dev]
  command = "npm start"
  port = 3000
  functionsPort = 9999
