[build]
  command = "npm install && npm run build"
  publish = "frontend/build"
  functions = "backend/functions"

[[redirects]]
  from = "/api/weather"
  to = "/.netlify/functions/weather"
  status = 200
  force = true

[[redirects]]
  from = "/api/projects"
  to = "/.netlify/functions/api/projects"
  status = 200
  force = true
