[build]
  command = "npm install && npm run build"  
  publish = "frontend/build"  
  functions = "backend/functions"  # ✅ This should match the `functions` folder

[dev]
  command = "npm start"
  port = 3000
  functionsPort = 9999
